language: node_js
node_js:
# TODO add this back once `nvs` on windows is fixed
#  - lts/*
  - node
os:
  - linux
  - windows
dist: focal
arch: arm64
env:
  - YARN_GPG=no
cache:
  directories:
    - $HOME/.yarn/berry/cache
